export { Benefits} from './Benefits/Benefits'
export { BenefitsCard} from './Benefits/BenefitsCard'
export { Breadcrumbs } from './Breadcrumbs/Breadcrumbs'
export { CartCard } from './CartCard/CartCard'
export { Collection } from './Collection/Collection'
export { CollectionCard } from './Collection/CollectionCard'
export { Hero } from './Hero/Hero'
export { ShopCard } from './ShopCard/ShopCard'
export { Team } from './Team/Team'
export { TeamSlider } from './Team/TeamSlider'

